# Generated by Django 6.1.1 on 2026-10-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('role', models.CharField(choices=[('seller', 'Vendedor'), ('manager', 'Gerente')], max_length=20, verbose_name='cargo')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='salário')),
                ('hired_on', models.DateField(verbose_name='admissão')),
            ],
            options={
                'verbose_name': 'funcionário',
                'verbose_name_plural': 'funcionários',
                'ordering': ('name',),
                'permissions': [('view_salary', 'Pode ver o salário')],
            },
        ),
    ]
